### ISSUE TITLE
List.Count in the method of  ToEntityList<>  

### ISSUE THREAD

**Issue by zhangze123** [WeihanLi/WeihanLi.Npoi#100] opened 2021-02-14 11:43 UTC
If you have 2 rows of data, use the format brush to process the following 3 rows of the table. The List.Count = 5 after use ToEntityList<> .

**Comment by WeihanLi** [comment] 2021-02-14 16:32
Yeah, we treat `null` as empty line, when you export a `null` value it will generate empty line, you can use `WithDataValidation` filter to filter out null value or you can set the `RowFilter` to limit the row read, you can take this for example <https://www.cnblogs.com/weihanli/p/13663897.html>/<https://www.cnblogs.com/weihanli/p/13934396.html>

**Comment by WeihanLi** [comment] 2021-02-28 06:55
close this for that's by design, you can reopen it if you have more questions

**Closed by WeihanLi** 2021-02-28 06:55 UTC
